

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/SwapValues:
  Enabled: true

Minitest/AssertInDelta:
  Enabled: true

Minitest/AssertionInLifecycleHook:
  Enabled: true

Minitest/AssertKindOf:
  Enabled: true

Minitest/AssertOutput:
  Enabled: true

Minitest/AssertPathExists:
  Enabled: true

Minitest/AssertSilent:
  Enabled: true

Minitest/LiteralAsActualArgument:
  Enabled: true

Minitest/MultipleAssertions:
  Enabled: true

Minitest/RefuteInDelta:
  Enabled: true

Minitest/RefuteKindOf:
  Enabled: true

Minitest/RefutePathExists:
  Enabled: true

Minitest/TestMethodName:
  Enabled: true

Minitest/UnspecifiedException:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Gemspec/DateAssignment:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/StringChars:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/RedundantEqualityComparisonBlock:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Security/IoMethods:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Naming/BlockForwarding:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/OpenStructUse:
  Enabled: true

Performance/ConcurrentMonotonicTime:
  Enabled: true

Performance/StringIdentifierArgument:
  Enabled: true

Minitest/AssertWithExpectedArgument:
  Enabled: true

Minitest/UnreachableAssertion:
  Enabled: true
