require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance

inherit_from:
  - .rubocop_pending.yml
  - .rubocop_be_pedantic.yml

AllCops:
  TargetRubyVersion: 2.6

# I like parallel assignment.
Style/ParallelAssignment:
  Enabled: false

# imho
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Don't enforce block brace spaces in tests
# because _{foo} is common there and matches _(foo), _ { foo } looks weird because it doesn't match _(foo)
Layout/SpaceInsideBlockBraces:
  Exclude:
    - 'test/**/*'
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'test/**/*'

# Not a relevant metric for tests, where we organise tests by block and those blocks get pretty large
# Also not relevant for gemspec
Metrics/BlockLength:
  Exclude:
    - 'test/**'
    - runeterra_cards.gemspec

# Just no.
Style/AsciiComments:
  Enabled: false
