language: ruby
rvm:
  - 2.6
  - 2.7

before_install:
  - gem install bundler -v ~> 2

script: bundle exec rake test

jobs:
  include:
    - stage: test-3.0.0-preview1
      before_install: rvm get head && rvm reload && rvm use --install 3.0.0-preview1
    - stage: lint
      rvm: 2.7
      script: bundle exec rake all_checks
