name: Continuous Integration
on: [push, pull_request]
jobs:
  all-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rake all_checks
  unit-tests-matrix:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, head, jruby-9.1.17.0, jruby, jruby-head, truffleruby, truffleruby-head]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rake test
