name: Lint
on:
  push:
    branches: development
  pull_request:
jobs:
  coverage:
    name: Coverage/mutation testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: "Debug: environment"
        run: |
          ruby --version
          bundler --version
      - name: Mutation testing
        run: bundle exec rake mutation_test
  linters:
    name: Rubocop & docs linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: "Debug: environment"
        run: |
          ruby --version
          bundler --version
      - name: Rubocop
        run: bundle exec rake rubocop
      - name: Lint docs
        run: bundle exec rake verify_docs
