name: Test
on:
  push:
    branches: development
  pull_request:
jobs:
  unit-tests-matrix:
    name: Unit tests matrix
    strategy:
      fail-fast: false
      matrix:
        ruby: ["jruby", "truffleruby", "2.3", "2.4", "2.5", "2.6", "2.7", "3.0", "head"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: "Debug: environment"
        run: |
          ruby --version
          bundler --version
      - name: Run tests
        run: bundle exec rake test
