name: Test
on:
  push:
    branches: development
  pull_request:
jobs:
  unit-tests-matrix:
    name: Unit tests matrix
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "2.7", "2.6", "head", "jruby-9.3", "jruby-head", "truffleruby-20", "truffleruby-21", "truffleruby-head"]
        os: [ubuntu-latest, windows-latest]
        ignore_failure: [false]
        exclude:
          - os: windows-latest
            ruby: truffleruby-20
          - os: windows-latest
            ruby: truffleruby-21
          - os: windows-latest
            ruby: truffleruby-head
          - os: windows-latest
            ruby: jruby-9.3
          - os: windows-latest
            ruby: jruby-head
        include:
          - os: windows-latest
            ruby: jruby-9.3
            ignore_failure: true
          - os: windows-latest
            ruby: jruby-head
            ignore_failure: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.ignore_failure }}
    env:
      SKIP_MUTANT_LICENSE: 1
      BUNDLE_WITHOUT: development
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: "Debug: environment"
        run: |
          ruby --version
          bundler --version
      - name: Run tests
        run: bundle exec rake test
